Repository facebook/instant-articles-builder, pull requests merged in 2021-04, with the labels that each got.

#171 Warnings improvements
  src/js/components/Preview.react.js
  src/js/components/Warnings.react.js
  webserver/article.php
Labels: CLA Signed, cla signed

#172 Upgrade webserver IA SDK to v1.10.2
  webserver/composer.json
  webserver/composer.lock
Labels: CLA Signed, cla signed

#173 Use GitHub URL for preview logo
  webserver/styles/default.style.json
Labels: CLA Signed, cla signed

#177 Bump version to v0.2.3
  package-lock.json
  package.json
  src/js/version.js
Labels: CLA Signed

#176 Upgrade build web server PHP version to 7.4.9
  build.sh
Labels: CLA Signed, enhancement
